// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using noteit_aspnetserver.Data;

#nullable disable

namespace noteit_aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230413002753_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("noteit_aspnetserver.Data.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            Content = "This is a note 1 and Lorem ipsum...",
                            Title = "Note 1"
                        },
                        new
                        {
                            NoteId = 2,
                            Content = "This is a note 2 and Lorem ipsum...",
                            Title = "Note 2"
                        },
                        new
                        {
                            NoteId = 3,
                            Content = "This is a note 3 and Lorem ipsum...",
                            Title = "Note 3"
                        },
                        new
                        {
                            NoteId = 4,
                            Content = "This is a note 4 and Lorem ipsum...",
                            Title = "Note 4"
                        },
                        new
                        {
                            NoteId = 5,
                            Content = "This is a note 5 and Lorem ipsum...",
                            Title = "Note 5"
                        },
                        new
                        {
                            NoteId = 6,
                            Content = "This is a note 6 and Lorem ipsum...",
                            Title = "Note 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
